# Site settings
title: "Joyce Blog" # the name of your site, e.g. ACME Corp.
SEOTitle: 房梅梅的博客 | Joyce Blog  # 用于SEO搜索时使用，|分开关键词
# header-img: #默认头部展示图片
description: "房志梅 描述"  #用作书签页面的默认描述
keyword: "房志梅 搜索关键词"
url: "https://joycefangmm.github.io/myBlankBlog"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'


# Publish posts or collection documents with a future date.
# ture未来时间的博客可以展示；false未来时间的博客不可以展示，直到时间发生才可以展示
future: false


# SNS settings
RSS: true
# weibo_username:     
github_username:    joycefangmm
twitter_username:   joycefangmm
# linkedin_username:  


# Build settings
highlighter: rouge
permalink: pretty 
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true  


# Gems
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]


# Markdown settings
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown  #支持目录生成
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1


# 房志梅，等待验证
# Gitalk settings
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: e3407be01d4fdeb5fd73                           #生成的clientID
  clientSecret: 6b1de3d60d14c0f3bf2ffb931ecc2991849cceea     #生成的clientSecret
  repo: joycefangmm.github.io    #仓库名称
  owner: joycefangmm    #github用户名
  admin: joycefangmm
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# Google Analytics
ga_track_id: 'UA-134920416-1'            # Format: UA-xxxxxx-xx
ga_domain: joycefangmm.github.io


# Sidebar settings
sidebar: true         
sidebar-about-description: "房志梅侧边栏文案描述"       # 侧边栏文案描述
sidebar-avatar: /assets/img/avatar-joyce-ny.png      # 侧边栏，关于使用的图片, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true                     # 是否展示
featured-condition-size: 1              # 当tag数超过多少时展示


# Progressive Web Apps
chrome-tab-theme-color: "#ffffff"  #比如，WPA状态栏颜色
service-worker: true

# MathJax，page预览可能存在，比如首页index，但大多数时候再预览中不会出现
page-mathjax: false


# Friends，好友的博客地址，房志梅删除掉
friends: [
  {
    title: "房志梅测试",
    href: "https://www.bing.com"
  },
  {
    title: "房志梅2测试",
    href: "https://www.bing.com"
  },
]